# Generated by Django 5.2.16 on 2026-07-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('purpose', models.TextField()),
                ('meeting_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_visits', to='employee.employee')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
