# Generated by Django 5.2.16 on 2026-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_phone_number'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='visit_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='clientvisit',
            index=models.Index(fields=['employee', 'visit_date'], name='visits_clie_employe_909b29_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvisit',
            index=models.Index(fields=['employee', 'status'], name='visits_clie_employe_01597c_idx'),
        ),
    ]
