from io import BytesIO

from django.http import HttpResponse
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT


def build_pdf_response(context):
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        name="TitleStyle",
        parent=styles["Heading1"],
        fontSize=18,
        leading=24,
        textColor=colors.HexColor("#1f4e79"),
        spaceAfter=0.15 * inch,
        alignment=TA_CENTER,
    )
    heading_style = ParagraphStyle(
        name="HeadingStyle",
        parent=styles["Heading2"],
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#2f4f4f"),
        spaceAfter=0.08 * inch,
    )
    subheading_style = ParagraphStyle(
        name="SubheadingStyle",
        parent=styles["BodyText"],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#475569"),
        spaceAfter=0.04 * inch,
    )
    normal_style = styles["BodyText"]

    def add_footer(canvas, doc):
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#64748b"))
        canvas.drawString(0.75 * inch, 0.55 * inch, "Field Visit Tracker")
        canvas.drawCentredString(4.25 * inch, 0.55 * inch, "Confidential Internal Report")
        canvas.drawRightString(7.25 * inch, 0.55 * inch, f"Page {doc.page}")

    story = []
    story.append(Paragraph("FIELD VISIT TRACKER REPORT", title_style))
    story.append(Spacer(1, 0.08 * inch))
    story.append(Paragraph(f"Generated Date: {context.get('generated_date', '')}", subheading_style))
    story.append(Paragraph(f"Generated Time: {context.get('generated_time', '')}", subheading_style))
    story.append(Paragraph(f"Generated By: {context.get('generated_by', '')}", subheading_style))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("Applied Filters", heading_style))
    story.append(Paragraph(f"From Date: {context.get('from_date') or 'All'}", normal_style))
    story.append(Paragraph(f"To Date: {context.get('to_date') or 'All'}", normal_style))
    story.append(Paragraph(f"Employee: {context.get('employee_name') or 'All'}", normal_style))
    story.append(Paragraph(f"Visit Status: {context.get('visit_status') or 'All'}", normal_style))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Summary", heading_style))
    summary_data = [
        ["Total Attendance Records", str(context.get("total_attendance_records", 0))],
        ["Total Present", str(context.get("total_present", 0))],
        ["Total Client Visits", str(context.get("total_client_visits", 0))],
        ["Pending Visits", str(context.get("pending_visits", 0))],
        ["Completed Visits", str(context.get("completed_visits", 0))],
    ]
    summary_table = Table(summary_data, colWidths=[3 * inch, 1.5 * inch])
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f7f9fc")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d9dee8")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e9f2ff")),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 0.25 * inch))

    story.append(Paragraph("Visit Details", heading_style))
    visits = context.get("visits", [])
    if visits:
        # Build Paragraph styles for table cells so long text wraps correctly
        cell_style = ParagraphStyle(
            name="TableCell",
            parent=styles["BodyText"],
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#000000"),
            alignment=TA_LEFT,
        )
        header_cell_style = ParagraphStyle(
            name="TableHeaderCell",
            parent=styles["BodyText"],
            fontSize=10,
            leading=12,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#1f4e79"),
        )

        # Create header row with Paragraphs
        header = [
            Paragraph("Employee", header_cell_style),
            Paragraph("Client Name", header_cell_style),
            Paragraph("Company Name", header_cell_style),
            Paragraph("Visit Date", header_cell_style),
            Paragraph("Status", header_cell_style),
        ]

        table_rows = [header]
        for visit in visits:
            emp = visit.employee.name if visit.employee else "-"
            table_rows.append(
                [
                    Paragraph(emp, cell_style),
                    Paragraph(visit.client_name or "-", cell_style),
                    Paragraph(visit.company_name or "-", cell_style),
                    Paragraph(str(visit.visit_date), ParagraphStyle(name="DateCell", parent=cell_style, alignment=TA_CENTER)),
                    Paragraph(visit.status or "-", ParagraphStyle(name="StatusCell", parent=cell_style, alignment=TA_CENTER)),
                ]
            )

        # Calculate column widths to fit within page margins (letter width 8.5in, margins total 1.5in -> usable 7.0in)
        details_col_widths = [2.0 * inch, 2.0 * inch, 1.7 * inch, 0.8 * inch, 0.5 * inch]

        details_table = Table(table_rows, repeatRows=1, colWidths=details_col_widths)
        details_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e9f2ff")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d9dee8")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#1f4e79")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("ALIGN", (0, 1), (2, -1), "LEFT"),
                    ("ALIGN", (3, 1), (4, -1), "CENTER"),
                ]
            )
        )
        story.append(details_table)
    else:
        story.append(Paragraph("No records found.", normal_style))

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    pdf = buffer.getvalue()
    buffer.close()

    response = HttpResponse(pdf, content_type="application/pdf")
    response["Content-Disposition"] = 'attachment; filename="Field-Visit-Report.pdf"'
    return response
