# Generated by Django 5.2.16 on 2026-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
