# Generated by Django 5.2.16 on 2026-07-17 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Employee Created', 'Employee Created'), ('Employee Updated', 'Employee Updated'), ('Check In', 'Check In'), ('Check Out', 'Check Out'), ('Visit Created', 'Visit Created'), ('Visit Completed', 'Visit Completed'), ('Report Generated', 'Report Generated')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
