# Generated by Django 5.2.16 on 2026-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Late', 'Late')], default='Checked In', max_length=20),
        ),
    ]
